version: "3.9"

services:
  bot:
    build: .
    image: smaystr-bot:latest
    restart: unless-stopped
    env_file:
      - .env
    # Add tmpfs volumes for temporary files access
    volumes:
      - ./.tmp:/tmp
      - ./.var_tmp:/var/tmp
      - ./.usr_tmp:/usr/tmp
    tmpfs:
      - /tmp:exec,mode=1777
      - /var/tmp:exec,mode=1777
      - /usr/tmp:exec,mode=1777
    # optional health-check – ping via Telegram API could be scripted
    # healthcheck:
    #   test: ["CMD", "/app/smaystr-bot", "--health"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3 